#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0
"""
Fit the on-device genre model from labelled feature rows.

Rows come from `analyze_wav --csv <genre> file.wav` or from collect_mqtt.py
(recorded by the gateway's own microphone, which is the better calibration).
Each row is: genre,source,v0..v8 with the vector from genre_feature_vector().

    python3 fit_genre_model.py data/*.csv            # report leave-one-source-out accuracy
    python3 fit_genre_model.py data/*.csv -o ../main/genre_model.h

Only the Python standard library is needed.
"""

import argparse
import csv
import math
import sys
from collections import defaultdict

GENRES = ['silence', 'ambient', 'classical', 'pop', 'rock', 'electronic', 'hiphop']
FEATURES = ['tempo', 'regularity', 'contrast', 'onset_rate', 'bass', 'mid', 'high', 'range', 'centroid']
# Floor on each per-genre spread, as a fraction of the overall spread, so a
# genre recorded from one song does not become impossibly narrow.
STD_FLOOR = 0.25


def load(paths):
    rows = []
    for path in paths:
        with open(path, newline='') as f:
            for r in csv.reader(f):
                if not r or r[0].startswith('#'):
                    continue
                if r[0] not in GENRES[1:]:
                    sys.exit('{}: unknown genre "{}", use one of {}'.format(path, r[0], ', '.join(GENRES[1:])))
                if len(r) != 2 + len(FEATURES):
                    sys.exit('{}: expected {} columns, got {}'.format(path, 2 + len(FEATURES), len(r)))
                rows.append((r[0], r[1], [float(x) for x in r[2:]]))
    return rows


def mean_std(vectors):
    n = len(vectors)
    mean = [sum(v[i] for v in vectors) / n for i in range(len(FEATURES))]
    std = [math.sqrt(sum((v[i] - mean[i]) ** 2 for v in vectors) / n) for i in range(len(FEATURES))]
    return mean, std


def fit(rows):
    _, overall_std = mean_std([v for _, _, v in rows])
    by_genre = defaultdict(list)
    for g, _, v in rows:
        by_genre[g].append(v)
    model = {}
    for g, vectors in by_genre.items():
        mean, std = mean_std(vectors)
        std = [max(s, STD_FLOOR * o, 1e-3) for s, o in zip(std, overall_std)]
        model[g] = (mean, std)
    return model


def predict(model, v):
    best, best_ll = None, -math.inf
    for g, (mean, std) in model.items():
        ll = -sum(0.5 * ((x - m) / s) ** 2 + math.log(s) for x, m, s in zip(v, mean, std))
        if ll > best_ll:
            best, best_ll = g, ll
    return best


def evaluate(rows):
    """Leave one source (song or recording) out, so a song never tests itself."""
    sources = sorted({s for _, s, _ in rows})
    correct = defaultdict(int)
    total = defaultdict(int)
    confusion = defaultdict(lambda: defaultdict(int))
    for src in sources:
        train = [r for r in rows if r[1] != src]
        model = fit(train)
        for g, s, v in rows:
            if s != src:
                continue
            p = predict(model, v)
            total[g] += 1
            correct[g] += p == g
            confusion[g][p] += 1
    print('Leave-one-source-out accuracy over {} sources:'.format(len(sources)))
    for g in GENRES[1:]:
        if total[g]:
            mix = ' '.join('{}:{}'.format(p, n) for p, n in sorted(confusion[g].items(), key=lambda x: -x[1]))
            print('  {:<10} {:3d}/{:<3d} {:5.1%}   {}'.format(g, correct[g], total[g], correct[g] / total[g], mix))
    n, c = sum(total.values()), sum(correct.values())
    print('  {:<10} {:3d}/{:<3d} {:5.1%}'.format('all', c, n, c / n))


def write_header(model, path):
    def arr(values):
        return '{' + ', '.join('{:.5f}f'.format(x) for x in values) + '}'

    zero = [0.0] * len(FEATURES)
    one = [1.0] * len(FEATURES)
    lines = [
        '/*',
        ' * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD',
        ' *',
        ' * SPDX-License-Identifier: Apache-2.0',
        ' */',
        '',
        '/* Generated by host_test/fit_genre_model.py, do not edit. */',
        '',
        '#pragma once',
        '',
        '#define GENRE_MODEL_TRAINED 1',
        '',
        '_Static_assert(GENRE_FEATURE_COUNT == {}, "regenerate genre_model.h");'.format(len(FEATURES)),
        '',
        'static const unsigned char genre_model_present[MUSIC_GENRE_MAX] = {' +
        ', '.join('1' if g in model else '0' for g in GENRES) + '};',
        '',
        '/* Features: ' + ', '.join(FEATURES) + ' */',
        'static const float genre_model_mean[MUSIC_GENRE_MAX][GENRE_FEATURE_COUNT] = {',
    ]
    lines += ['    {}, /* {} */'.format(arr(model[g][0] if g in model else zero), g) for g in GENRES]
    lines += ['};', '', 'static const float genre_model_std[MUSIC_GENRE_MAX][GENRE_FEATURE_COUNT] = {']
    lines += ['    {}, /* {} */'.format(arr(model[g][1] if g in model else one), g) for g in GENRES]
    lines += ['};', '']
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print('Wrote {} with genres: {}'.format(path, ', '.join(g for g in GENRES if g in model)))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('csv', nargs='+', help='labelled feature rows')
    ap.add_argument('-o', '--output', help='write the model header, e.g. ../main/genre_model.h')
    args = ap.parse_args()

    rows = load(args.csv)
    if not rows:
        sys.exit('no rows')
    counts = defaultdict(int)
    for g, _, _ in rows:
        counts[g] += 1
    print('Rows per genre: ' + ', '.join('{} {}'.format(g, counts[g]) for g in GENRES[1:] if counts[g]))
    if len({s for _, s, _ in rows}) > 1:
        evaluate(rows)
    if args.output:
        write_header(fit(rows), args.output)


if __name__ == '__main__':
    main()
